[package]
name = "saltminer-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.saltminer-core]
path = "../crates/saltminer-core"

[[bin]]
name = "parse_phc"
path = "fuzz_targets/parse_phc.rs"
test = false
doc = false
bench = false

[workspace]
